### ISSUE TITLE
Unauthorized access error

### ISSUE THREAD

**Issue by allbombson** [ambrosethebuild/online-banking#4]
i get Unauthorized access  when trying to log in

**Comment by ambrosethebuild** [comment]
I just notice you forked the project and in your README.md and repository description you wrote 

> An Online Banking Platform Built With Laravel for the purpose of scam baiting (?)

Please be aware that the main purpose of the project was for educational purpose. I saw a UI sample on uplabs.com and decided to made a project out for it for learning purpose.
Thank you

**Comment by allbombson** [comment]
Ah understandable so i assume this has not been maintained, the purpose of that message was the fact I'm adding many things to make it more usable for scambaiting.
